version: '3.8'

services:
  media-service:
    build:
      context: ./server/media-service  # Path to the media-service folder
      dockerfile: Dockerfile
    ports:
      - "8082:8080" 
    environment:
      - MONGO_URI=mongodb://mongo-media:27017/your_media_database_name
    depends_on:
      - mongo
    networks:
      - lms-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - lms-network
  
  mongo-media:
    image: mongo:6.0
    container_name: mongo-media
    ports:
      - "27018:27017"
    volumes:
      - mongo-media-data:/data/db
    networks:
      - lms-network

  inventory-service:
    build:
      context: ./server/inventory-service
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/your_database_name
    depends_on:
      - mongo
    networks:
      - lms-network
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_INVENTORY_SERVICE_URL=http://inventory-service:3000/api/inventory
      - NEXT_PUBLIC_MEDIA_SERVICE_URL=http://media-service:8080
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app          # Map the local client folder to the container
      - /app/node_modules  
    depends_on:
      - media-service
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  mongo-data:
  mongo-media-data:
