version: '3.8'

services:
  inventory-service:
    build:
      context: ./server/inventory-service
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/your_database_name
      - MEDIA_SERVICE_URL=http://media-service:8080/api/media
      - WISHLIST_SERVICE_URL=http://wishlist-service:3000/api/wishlist
    depends_on:
      - mongo
    networks:
      - lms-network

  media-service:
    build:
      context: ./server/media-service  # Path to the media-service folder
      dockerfile: Dockerfile
    ports:
      - "8082:8080" 
    environment:
      - MONGO_URI=mongodb://mongo-media:27017/your_media_database_name
      - INVENTORY_SERVICE_URL=http://inventory-service:3000/api/inventory
      - NOTIFICATION_SERVICE_URL=http://notification-service:3000/api/notification
    depends_on:
      - mongo
    networks:
      - lms-network

  wishlist-service:
    build:
      context: ./server/wishlist-service
    ports:
      - "3003:3000"
    environment:
      - MONGO_URI=mongodb://mongo-media:27017/wishlist-data
      - INVENTORY_SERVICE_URL=http://inventory-service:3000/api/inventory
      - NOTIFICATION_SERVICE_URL=http://notification-service:3000/api/notification
    depends_on:
      - mongo
    networks:
      - lms-network


  notification-service:
    build:
      context: ./server/notification-service  # Path to the Express.js microservice folder
    ports:
      - "3002:3000"  # Expose container's port 3000 on host port 3002
    environment:
      - EMAIL_USER=cantorlibrarynotification@gmail.com
      - EMAIL_PASS=fkrv gcys cale qxwf
    networks:
      - lms-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - lms-network
  
  mongo-media:
    image: mongo:6.0
    container_name: mongo-media
    ports:
      - "27018:27017"
    volumes:
      - mongo-media-data:/data/db
    networks:
      - lms-network
  
  mongo-wishlist:
    image: mongo:6.0
    container_name: mongo-wishlist
    ports:
      - "27019:27017"
    volumes:
      - mongo-wishlist-data:/data/db
    networks:
      - lms-network
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_INVENTORY_SERVICE_URL=http://inventory-service:3000/api/inventory
      - NEXT_PUBLIC_MEDIA_SERVICE_URL=http://media-service:8080/api/media
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app          # Map the local client folder to the container
      - /app/node_modules  
    depends_on:
      - media-service
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  mongo-data:
  mongo-media-data:
  mongo-wishlist-data: